name: Go

on: [push, pull_request]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.21', '1.22.x' ]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
